name: Test Old TypeScript

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        typescript:
          - 4.8.4
          - 4.7.4
          - 4.6.4
          - 4.5.5
          - 4.4.4
          - 4.3.5
          - 4.2.3
          - 4.1.5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build
      - name: Patch for Old TS
        run: |
          sed -i~ 's/\/\/ @ts-expect-error.*\[LATEST-TS-ONLY\]//' tests/*.tsx
          sed -i~ 's/"target":/"skipLibCheck":true,"target":/' tsconfig.json
          sed -i~ 's/"exactOptionalPropertyTypes": true,//' tsconfig.json
          sed -i~ 's/"zustand": \["\.\/src\/index\.ts"\],/"zustand": [".\/dist\/index.d.ts"],/' tsconfig.json
          sed -i~ 's/"zustand\/\*": \["\.\/src\/\*\.ts"\]/"zustand\/*": [".\/dist\/*.d.ts"]/' tsconfig.json
          sed -i~ 's/"include": .*/"include": ["src\/types.d.ts", "dist\/**\/*", "tests\/**\/*"],/' tsconfig.json
      - name: Patch for Older TS
        if: ${{ matrix.typescript == '4.2.3' || matrix.typescript == '4.1.5' }}
        run: |
          sed -i~ 's/import\.meta\.env/(import.meta.env as any)/' tests/*.tsx
          sed -i~ 's/jest\.Mock<[^>]*>/jest.Mock<any,any>/g' tests/*.tsx
          cat tests/devtools.test.tsx
          yarn json -I -f package.json -e "this.resolutions['@jest/globals']='25.5.2';"
          yarn add -D @jest/globals@25.5.2
      - name: Test ${{ matrix.typescript }}
        run: |
          yarn add -D typescript@${{ matrix.typescript }}
          rm -r node_modules/@types/jsdom node_modules/parse5 node_modules/@types/prettier
          yarn tsc --noEmit
